services:
  web:
    build: .
    ports:
      - ${VITE_APP_PORT}:${VITE_APP_PORT}
    environment:
      MONGO_DB_ATLAS_HOST: ${MONGO_DB_ATLAS_HOST}
      MONGO_DB_ATLAS_USER: ${MONGO_DB_ATLAS_USER}
      MONGO_DB_ATLAS_PASSWORD: ${MONGO_DB_ATLAS_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${EXPRESS_SERVER_PORT}:${EXPRESS_SERVER_PORT}
    environment:
      MONGO_DB_ATLAS_HOST: ${MONGO_DB_ATLAS_HOST}
      MONGO_DB_ATLAS_USER: ${MONGO_DB_ATLAS_USER}
      MONGO_DB_ATLAS_PASSWORD: ${MONGO_DB_ATLAS_PASSWORD}
