export const stacks = {
    frontend: [
        "HTML",
        "CSS",
        "Sass",
        "Less",
        "Tailwinds",
        "Material UI",
        "Bootstrap",
        "JavaScript",
        "JSON",
        "XML",
        "jQuery",
        "Angular",
        "Vue",
        "React",
        "Backbone",
        "Ember",
        "Redux",
        "Storybook",
        "Meteorjs",
        "Grunt",
        "Gulp",
    ],
    backend: [
        "PHP",
        "ASP",
        "C++",
        "C#",
        "Java",
        "Python",
        "Node",
        "Express",
        "Ruby",
        "REST",
        "GraphQL",
        "Go",
        "MySQL", "Postgress", "MongoDB", "RDS", "DynamoDB", "SQL Server",
        "Firebase",
    ],
    cloud: [
        "EC2",
        "CloudFront",
        "EFS",
        "NAT Gateway",
        "Internet Gateway",
        "VPC",
        "IAM",
        "S3",
        "RDS",
        "ELB",
        "DynamoDB",
        "Lambda",
        "EBS",
        "SQS",
        "SNS",
        "Route 53",
        "Farget",
        "ECS",
        "Docker",
        "EKS"
    ],
    ux: [
        "Figma",
        "Adobe XD",
        "Sketch",
        "Marvel",
        "inVision",
        "Miro",
        "draw.io",
        "Framer",
        "Craft",
        "Lucidchart",
        "Balsamiq",
        "axure",
        "Proto",
        "Webflow",
        "FlowMapp"
    ]
}